name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Unit tests
                run: npm run test:unit
